# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  startdayily:
    docker:
      - image: circleci/node:16.10
    working_directory: ~/repo
    steps:
      - run: make setup build
      - run: make dailycheck

  startweekly:
    docker:
      - image: circleci/node:16.10
    working_directory: ~/repo
    steps:
      - run: make setup build
      - run: make weeklycheck


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  weather-alerts-dayily:
    triggers:
      - schedule:
          cron: "5 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - startweekly

  weather-alerts-weekly:
    triggers:
      - schedule:
          cron: "10 0 * * 7"
          filters:
            branches:
              only:
                - master
    jobs:
      - startdayily
