# This is a basic workflow to help you get started with Actions

name: Daily

# Controls when the action will run. 
on:
  schedule:
   - cron: "0 1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      LAT: ${{ secrets.LAT }}
      LONG: ${{ secrets.LONG }}
      THRESHOLD_WIND_GUST: ${{ secrets.THRESHOLD_WIND_GUST }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Setup project
        run: make setup build
      - name: Run Script
        run: make dailycheck
